branch: fix cp command
Function was badly named and caused this failure when trying to run git-maintain cp:
git-maintain/lib/branch.rb:110:in `block in execAction': undefined method `cp' for #<GitMaintain::RDMACoreBranch:0x0000000000e266e8> (NoMethodError)

Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>